#!/bin/bash
# deploy-free.sh - Deploy CodingJudge to FREE cloud (Oracle Cloud / Google Cloud Run)
# Usage: ./deploy-free.sh [oracle|gcp] [region]

set -e

PROVIDER=${1:-oracle}
REGION=${2:-us-ashburn-1}

echo "🚀 Free Deployment for CodingJudge"
echo "Provider: $PROVIDER | Region: $REGION"
echo ""

if [ "$PROVIDER" = "oracle" ]; then
    echo "📋 Oracle Cloud Free Tier Deployment"
    echo "======================================"
    echo ""
    echo "Prerequisites (do once):"
    echo "1. Sign up at: https://cloud.oracle.com/free"
    echo "2. Create ARM instance: 4 OCPUs, 24GB RAM, Ubuntu 22.04"
    echo "3. Add SSH key, open ports 22, 80, 443"
    echo "4. Note down: Public IP, Private IP"
    echo ""
    echo "Run on your Oracle instance:"
    echo "  curl -fsSL https://raw.githubusercontent.com/amansingh1207/Sitare_Coding_Platform/main/server-setup.sh | sudo bash"
    echo "  cd /opt/codingjudge"
    echo "  cp .env.prod.example .env.prod && nano .env.prod"
    echo "  docker compose -f docker-compose.prod.yml up -d"
    echo ""
    echo "Get SSL cert:"
    echo "  docker compose -f docker-compose.prod.yml run --rm certbot certonly --webroot -w /var/www/certbot -d yourdomain.com"
    echo "  docker compose -f docker-compose.prod.yml restart nginx"
    
elif [ "$PROVIDER" = "gcp" ]; then
    echo "☁️ Google Cloud Run - REQUIRES CREDIT CARD (even for free tier)"
    echo "================================================================"
    echo ""
    echo "⚠️  GCP REQUIRES credit card even for free tier!"
    echo "    If you don't have a credit card, SKIP this option."
    echo ""
    echo "Free tier: 2M requests/month, but requires billing account"
    echo ""

elif [ "$PROVIDER" = "railway" ]; then
    echo "🚂 Railway - REQUIRES CREDIT CARD (even for trial)"
    echo "===================================================="
    echo ""
    echo "⚠️  Railway REQUIRES credit card for verification!"
    echo "    If you don't have a credit card, SKIP this option."
    echo ""

elif [ "$PROVIDER" = "render" ]; then
    echo "🎨 Render Deployment (Free Tier - NO CREDIT CARD)"
    echo "================================================="
    echo ""
    echo "✅ NO CREDIT CARD REQUIRED for free tier!"
    echo ""
    echo "Free tier limits:"
    echo "  - Web services: Sleep after 15 min inactivity"
    echo "  - PostgreSQL: Free for 90 days only"
    echo "  - 100 GB bandwidth/month"
    echo "  - Auto SSL & custom domain"
    echo ""
    echo "Steps:"
    echo "1. Sign up at render.com (GitHub login, NO credit card)"
    echo "2. Create PostgreSQL database (free 90 days)"
    echo "3. Create Web Service for backend:"
    echo "   - Connect GitHub repo"
    echo "   - Build command: cd backend && mvn package -DskipTests"
    echo "   - Start command: java -jar target/codingjudge-backend-0.1.0.jar"
    echo "4. Create Static Site for frontend:"
    echo "   - Build command: cd frontend && npm run build"
    echo "   - Publish directory: frontend/dist"
    echo "5. Set environment variables in Render dashboard"
    echo ""
    echo "⚠️  Backend will sleep after 15 min inactivity (cold start ~30s)"
    echo "⚠️  PostgreSQL FREE for 90 days only, then paid"

elif [ "$PROVIDER" = "fly" ]; then
    echo "🪰 Fly.io - REQUIRES CREDIT CARD (even for free allowance)"
    echo "=========================================================="
    echo ""
    echo "⚠️  Fly.io REQUIRES credit card for verification!"
    echo ""

elif [ "$PROVIDER" = "koyeb" ]; then
    echo "🚀 Koyeb - NO CREDIT CARD for free tier!"
    echo "========================================="
    echo ""
    echo "✅ NO CREDIT CARD REQUIRED!"
    echo ""
    echo "Free tier:"
    echo "  - 1 free service (512MB RAM, 1 vCPU)"
    echo "  - 1 free PostgreSQL (1GB storage)"
    echo "  - Custom domain + auto SSL"
    echo "  - No sleep!"
    echo ""
    echo "Steps:"
    echo "1. Sign up at koyeb.com (GitHub login, NO credit card)"
    echo "2. Create App from GitHub repo"
    echo "3. Add PostgreSQL addon (free)"
    echo "3. Set build: Dockerfile"
    echo "4. Set env vars in Koyeb dashboard"
    echo "5. Deploy!"

elif [ "$PROVIDER" = "koyeb-postgres" ]; then
    echo "🐘 Koyeb + External Free PostgreSQL (Supabase/Neon)"
    echo "====================================================="
    echo ""
    echo "✅ 100% FREE - NO CREDIT CARD!"
    echo ""
    echo "Option 1: Supabase (PostgreSQL - FREE forever)"
    echo "  1. Sign up at supabase.com (GitHub login)"
    echo "  2. Create project → Get connection string"
    echo "  3. Use in Koyeb/Render/Railway as external DB"
    echo ""
    echo "Option 2: Neon (PostgreSQL - FREE forever)"
    echo "  1. Sign up at neon.tech (GitHub login)"
    echo "  2. Create project → Get connection string"
    echo "  3. Use as external DB"
    echo ""
    echo "Best combo: Koyeb (backend+frontend) + Supabase (PostgreSQL) = 100% FREE forever!"

else
    echo "Usage: ./deploy-free.sh [oracle|gcp|railway|render] [region]"
    echo ""
    echo "Best FREE options:"
    echo "  oracle  - Oracle Cloud Free Tier (Always free, 4 ARM CPUs, 24GB RAM) ⭐ RECOMMENDED"
    echo "  gcp     - Google Cloud Run (2M req/mo free)"
    echo "  railway - Railway.app (\$5/mo credit)"
    echo "  render  - Render.com (sleeps after 15min)"
    exit 1
fi

echo ""
echo "📋 Common Steps for ALL providers:"
echo "=================================="
echo "1. Set up DNS: Point your domain to the provided IP/URL"
echo "2. Configure .env.prod with real values"
echo "3. Get SSL cert (Let's Encrypt - FREE)"
echo "4. Test: https://yourdomain.com"
echo ""
echo "🔑 Required .env.prod values:"
echo "  DB_PASSWORD=strong_random_password"
echo "  JWT_SECRET=256_bit_random_string"
echo "  MAIL_USERNAME=your@gmail.com"
echo "  MAIL_PASSWORD=gmail_app_password"
echo "  DOMAIN=yourdomain.com"
echo ""
echo "📚 Full guide: DEPLOYMENT.md"